[package]
name = "uint"
version = "0.1.0"
authors = ["Remco Bloemen <remco@wicked.ventures>"]
edition = "2021"

[features]
default = []
bench = [ "criterion", "proptest" ]

[[bench]]
name = "criterion"
harness = false
path = "criterion.rs"
required-features = [ "bench", "proptest" ]

[dependencies]
itertools = "0.10"
criterion = { version = "0.3", optional = true }
proptest = { version = "1.0", optional = true }
static_assertions = "1.1"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1.0"
proptest = { version = "1.0" }

# Compilation profile for any non-workspace member.
# Dependencies are optimized, even in a dev build. This improves dev performance
# while having neglible impact on incremental build times.
[profile.dev.package."*"]
opt-level = 3

# Produce debug info for release builds
[profile.release]
debug = true
