[package]
name = "uint"
description = "Unsigned integer type with cont-generic bit length"
authors = ["Remco Bloemen <remco@wicked.ventures>"]
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/recmo/uint"
repository = "https://github.com/recmo/uint"
keywords = ["uint"]
categories = ["mathematics"]
readme = "Readme.md"
license-file = "mit-license.md"

[workspace]
members = ["uint-macro"]

[features]
default = []
bench = [ "criterion", "proptest" ]

[[bench]]
name = "criterion"
harness = false
path = "criterion.rs"
required-features = [ "bench", "proptest" ]

[dependencies]
itertools = "0.10"
thiserror = "1.0"
uint-macro = { version = "0.1.0", path = "./uint-macro" }

# Optional
rand = { version = "0.8", optional = true }
quickcheck = { version = "1.0", optional = true }
proptest = { version = "1.0", optional = true }
arbitrary = { version = "1.1", optional = true }
serde = { version = "1.0", optional = true }

# Secretly dev-dependencies
criterion = { version = "0.3", optional = true }

[dev-dependencies]
pretty_assertions = "1.0"
proptest = { version = "1.0" }
serde_json = "1.0"
bincode = "1.3"

# Compilation profile for any non-workspace member.
# Dependencies are optimized, even in a dev build. This improves dev performance
# while having neglible impact on incremental build times.
[profile.dev.package."*"]
opt-level = 3

# Produce debug info for release builds
[profile.release]
debug = true

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", ".cargo/katex-header.html" ]
