[package]
name = "ruint"
description = "Unsigned integer type with cont-generic bit length"
authors = ["Remco Bloemen <remco@wicked.ventures>"]
version = "0.2.0"
edition = "2021"
homepage = "https://github.com/recmo/uint"
repository = "https://github.com/recmo/uint"
keywords = ["uint"]
categories = ["mathematics"]
readme = "Readme.md"
license = "MIT"

[workspace]
members = ["ruint-macro"]

[features]
default = []
bench = [ "criterion", "proptest" ]
dyn = [ "smallvec"]
generic_const_exprs = []

[[bench]]
name = "criterion"
harness = false
path = "criterion.rs"
required-features = [ "bench", "proptest" ]

[dependencies]
itertools = "0.10"
thiserror = "1.0"
ruint-macro = { version = "0.2.0", path = "./ruint-macro" }

# UintDyn
smallvec = { version = "1.8.0", optional = true, features = [ "union" ] }

# Optional
rand = { version = "0.8.5", optional = true }
quickcheck = { version = "1.0", optional = true }
proptest = { version = "1.0", optional = true }
arbitrary = { version = "1.1", optional = true }
serde = { version = "1.0", optional = true }
rlp = { version = "0.5.1", optional = true }
fastrlp = { version = "0.1.0", optional = true }
primitive-types = { version = "0.11.1", optional = true }

# Secretly dev-dependencies
criterion = { version = "0.3", optional = true }

[build-dependencies]
# Rust currently has no way to conditionally compile based on compiler features.
# `autocfg` is a workaround, but doesn't support probing for `#[features(...)]`
# yet. Luckily a PR adds this support.
autocfg = { version = "1.1", git = "https://github.com/CAD97/autocfg", rev = "a1d7429b90a6a306626d759d8cc6c8558c8f79cd" }

[dev-dependencies]
proptest = { version = "1.0" }
serde_json = "1.0"
bincode = "1.3"
hex-literal = "0.3.4"

# Compilation profile for any non-workspace member.
# Dependencies are optimized, even in a dev build. This improves dev performance
# while having neglible impact on incremental build times.
[profile.dev.package."*"]
opt-level = 3

# Produce debug info for release builds
[profile.release]
debug = true

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", ".cargo/katex-header.html" ]
