[alias]
criterion = "bench --bench=criterion --features=bench"

# This enables KaTex in docs, but requires runing `cargo doc --no-deps`.
[build]
rustdocflags = "--html-in-header .cargo/katex-header.html"
