name: Issue Tracker

on:
  push:
    branches: [ main ]

jobs:
  issue-tracker:
    name: Issue Tracker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: issue_tracker-${{ hashFiles('.github/workflows/issue_tracker.yml') }}
          restore-keys: issue_tracker-
      - name: Install Python dependencies
        run: pip install PyGithub
      - name: Update issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
        run: .github/scripts/issue_tracker.py
